[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
# Note: also change "version" in `constant.py`.
# Note: also operate `uv lock`.
name = "biz-dfch-incoseiso25010refiner"
version = "0.1.0"
description = "An INCOSE and ISO25010 requirements refiner."
readme = "README.md"
requires-python = ">=3.13"
license = "AGPL-3.0-or-later"
license-files = [
    "LICENSE",
]
authors = [
    {name = "Ronald Rink"},
]
maintainers = [
    { name = "d-fens GmbH" },
]

keywords = [
    "INCOSE",
    "ISO25010",
    "requirements",
    "technical writing",
    "technical-writing",
    "text processing",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "dacite>=1.9.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "typer>=0.25.1",
]

# Install with `uv`:
# uv sync --extra dev --extra build --python 3.13
# Examine if you can operate `unittest` correctly:
# uv run python -m unittest discover -v -s tests -t . -p "test_*.py"
# Examine if you can operate `pylint` correctly:
# uv run pylint $(git ls-files '*.py')
[project.optional-dependencies]
test = [
    "coverage",
    "parameterized>=0.9.0",
    "pylint>=4.0.0",
]

dev = [
    "biz-dfch-incoseiso25010refiner[test]",
    "black",
    "flake8>=7.3.0",
    "pip>=26.1.1",
]

interactive = [
    "ipykernel",
]

build = [
    "pyinstaller>=6.16.0",
]

[project.urls]
Homepage = "https://github.com/dfensgmbh/biz.dfch.IncoseIso25010Refiner"
Issues = "https://github.com/dfensgmbh/biz.dfch.IncoseIso25010Refiner/issues"

[project.scripts]  
req = "main:app"

[tool.black]
line-length = 80

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[[tool.mypy.overrides]]
module = ["parameterized.*"]
ignore_missing_imports = true
